### ISSUE TITLE
send notification to helper? very bad coding!

### ISSUE THREAD

**Issue by ghost** [nikobix/MMM-BinaryClock#1]
send notification to which helper? 

and icons are flickering very badly
you must make some improvements

**Comment by nikobix** [comment]
Hello Hangorazvan
Will take a look. I have only built this on my MM, which is running on a Pi3. This is only my 2nd module.

As for the helper, I will remove it as it is not needed, this is a fairly simple module.

Thanks

**Comment by nikobix** [comment]
Hello Hangorazvan

I have re-written the code to stop the constant DOM refresh. 
Hopefully this should reduce the flicker.

Let me know.

Thanks
Nik

**Comment by ghost** [comment]
flickering is gone but styling is totally mess, the module is over the clock if is on top_left.
You need to work on elements style, put all in container then position relative the container to div

**Comment by nikobix** [comment]
Thanks. 
I have manged to work out how to solve this. 
I had created a container, but forgot to set the size of the DIV container. 

I have just uploaded the latest version

Cheers

**Comment by hangorazvan** [comment]
This is what I get now from your module
![Untitled-1](https://user-images.githubusercontent.com/58172000/88672079-b7584d00-d0ef-11ea-96ce-39874c34a684.jpg)

and previosly
![2020-07-23 (2)](https://user-images.githubusercontent.com/58172000/88672274-f1c1ea00-d0ef-11ea-82aa-61828927e57a.png)
